file:
  upload-dir: ./uploads
spring:
  ai:
    vectorstore:
      redis:
        uri: ${REDIS}
        index: faqs
        prefix: "faq:"
        initialize-schema: true
    ollama:
      chat:
        model: llama3.1:latest
        options:
          temperature: 0.2
  application:
    name: spring-ollama-chat
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false